[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Mon Jun  2 22:56:04 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 9504
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x583d0700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x583d0700 pid: 22279 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 22279, cores: 1)
[pid: 22279|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 882 bytes} [Mon Jun  2 21:56:12 2025] GET /stream/ => generated 1538 bytes in 511 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./cameras/views.py", line 16, in gen
    from mediapipe.solutions import hands as mp_hands_module
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
[pid: 22279|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 21:56:13 2025] GET /video_feed/ => generated 0 bytes in 429 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
[pid: 22279|app: 0|req: 3/3] 127.0.0.1 () {46 vars in 882 bytes} [Mon Jun  2 22:05:22 2025] GET /stream/ => generated 1538 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[ WARN:0@549.450] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@549.450] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
Traceback (most recent call last):
  File "./cameras/views.py", line 16, in gen
    import cv2
ModuleNotFoundError: No module named 'mediapipe'
[pid: 22279|app: 0|req: 4/4] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 22:05:22 2025] GET /video_feed/ => generated 0 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Mon Jun  2 23:06:07 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 9504
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x573e0700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x573e0700 pid: 22394 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 22394, cores: 1)
[pid: 22394|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 882 bytes} [Mon Jun  2 22:06:08 2025] GET /stream/ => generated 1538 bytes in 242 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 22:06:19 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 22:06:19 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 22394|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 22:06:08 2025] GET /video_feed/ => generated 9235158 bytes in 10869 msecs (HTTP/1.1 200) 5 headers in 203 bytes (143 switches on core 0)
[pid: 22394|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 22:08:51 2025] GET / => generated 2348 bytes in 26 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Mon Jun  2 23:20:52 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x585f6700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x585f6700 pid: 1351 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1351, cores: 1)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Mon Jun  2 23:23:24 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x58098700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x58098700 pid: 1375 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1375, cores: 1)
Not Found: /favicon.ico
[pid: 1375|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 753 bytes} [Mon Jun  2 22:30:41 2025] GET /favicon.ico => generated 2633 bytes in 514 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Mon Jun  2 23:45:05 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x5679b700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5679b700 pid: 1418 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1418, cores: 1)
Not Found: /favicon.ico
[pid: 1418|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 753 bytes} [Mon Jun  2 22:54:02 2025] GET /favicon.ico => generated 2633 bytes in 489 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 1418|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:40:13 2025] GET / => generated 2348 bytes in 82 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:40:32 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57ae4700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57ae4700 pid: 23190 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23190, cores: 1)
[pid: 23190|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:40:33 2025] GET / => generated 2294 bytes in 636 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23190|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 837 bytes} [Mon Jun  2 23:40:35 2025] GET / => generated 2294 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23190|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 837 bytes} [Mon Jun  2 23:40:39 2025] GET / => generated 2294 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:41:14 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x5732c700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5732c700 pid: 23223 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23223, cores: 1)
[pid: 23223|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:41:15 2025] GET / => generated 2348 bytes in 441 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23223|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:41:18 2025] GET /stream/ => generated 1538 bytes in 12 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[ WARN:0@2.218] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@2.218] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
[pid: 23223|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:41:18 2025] GET /video_feed/ => generated 0 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:42:58 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x5806b700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5806b700 pid: 23252 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23252, cores: 1)
[pid: 23252|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:42:59 2025] GET / => generated 2348 bytes in 419 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23252|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:43:02 2025] GET /stream/ => generated 1538 bytes in 12 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[ WARN:0@2.637] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@2.637] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
[pid: 23252|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:43:02 2025] GET /video_feed/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
[pid: 23252|app: 0|req: 4/4] 127.0.0.1 () {46 vars in 882 bytes} [Mon Jun  2 23:43:13 2025] GET /stream/ => generated 1538 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:43:39 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:43:39 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23252|app: 0|req: 5/5] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:43:13 2025] GET /video_feed/ => generated 14581016 bytes in 25368 msecs (HTTP/1.1 200) 5 headers in 203 bytes (285 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:45:05 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57d64700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57d64700 pid: 23296 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23296, cores: 1)
[pid: 23296|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:45:06 2025] GET / => generated 2348 bytes in 448 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23296|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:45:11 2025] GET /stream/ => generated 1538 bytes in 7 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:45:45 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:45:45 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23296|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:45:11 2025] GET /video_feed/ => generated 20247661 bytes in 33728 msecs (HTTP/1.1 200) 5 headers in 203 bytes (389 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:46:28 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x58045700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x58045700 pid: 23322 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23322, cores: 1)
[pid: 23322|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:46:28 2025] GET / => generated 2348 bytes in 432 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23322|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:46:30 2025] GET / => generated 2348 bytes in 10 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23322|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:46:31 2025] GET /stream/ => generated 1538 bytes in 14 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:46:58 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:46:58 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23322|app: 0|req: 4/4] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:46:31 2025] GET /video_feed/ => generated 15672150 bytes in 27133 msecs (HTTP/1.1 200) 5 headers in 203 bytes (296 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:49:35 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57723700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57723700 pid: 23374 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23374, cores: 1)
[pid: 23374|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:49:36 2025] GET / => generated 2294 bytes in 1446 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23374|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:49:39 2025] GET / => generated 2294 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23374|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 837 bytes} [Mon Jun  2 23:49:41 2025] GET / => generated 2294 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
!!! uWSGI process 23374 got Segmentation Fault !!!
*** backtrace of 23374 ***
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_backtrace+0x32) [0x56648772]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_segfault+0x35) [0x56648b55]
linux-gate.so.1(__kernel_sigreturn+0) [0xf7fb0570]
/lib/i386-linux-gnu/libc.so.6(+0x7c873) [0xf770d873]
/lib/i386-linux-gnu/libc.so.6(+0x7d0a7) [0xf770e0a7]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xd7658) [0xf7950658]
/lib/i386-linux-gnu/libpython3.9.so.1.0(PyMem_RawFree+0x1d) [0xf79502bd]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xd7771) [0xf7950771]
/lib/i386-linux-gnu/libpython3.9.so.1.0(PyObject_Free+0x1d) [0xf79503dd]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xec709) [0xf7965709]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0x1c8399) [0xf7a41399]
/lib/i386-linux-gnu/libpython3.9.so.1.0(_PyGC_CollectNoFail+0x4f) [0xf7a4192f]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0x1857e7) [0xf79fe7e7]
/lib/i386-linux-gnu/libpython3.9.so.1.0(Py_FinalizeEx+0x22c) [0xf7a1efdc]
/lib/i386-linux-gnu/libpython3.9.so.1.0(Py_Finalize+0x14) [0xf7a1f294]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_python_atexit+0xe6) [0x566554e6]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_plugins_atexit+0x6b) [0x5664567b]
/lib/i386-linux-gnu/libc.so.6(+0x3388e) [0xf76c488e]
/lib/i386-linux-gnu/libc.so.6(+0x33a61) [0xf76c4a61]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(+0x23295) [0x565f6295]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(end_me+0x30) [0x566456d0]
linux-gate.so.1(__kernel_sigreturn+0) [0xf7fb0570]
linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7fb0559]
/lib/i386-linux-gnu/libc.so.6(epoll_wait+0x2c) [0xf779083c]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(event_queue_wait+0x2f) [0x5663a95f]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(wsgi_req_accept+0x102) [0x565f3532]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(simple_loop_run+0xd1) [0x56644411]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(simple_loop+0x8a) [0x5664452a]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_ignition+0x1e2) [0x56648e12]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_worker_run+0x270) [0x5664d7a0]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_run+0x464) [0x5664dcd4]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(+0x1f894) [0x565f2894]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106) [0xf76abed6]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(_start+0x31) [0x565f28d1]
*** end of backtrace ***
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:50:15 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x573af700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x573af700 pid: 23394 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23394, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./cameras/views.py", line 14, in camera_list
    cam.stream_url = request.build_absolute_uri(reverse('camera_stream'))  # or with ID if needed
NameError: name 'reverse' is not defined
[pid: 23394|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:50:16 2025] GET / => generated 54115 bytes in 1814 msecs (HTTP/1.1 500) 7 headers in 242 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./cameras/views.py", line 14, in camera_list
    cam.stream_url = request.build_absolute_uri(reverse('camera_stream'))  # or with ID if needed
NameError: name 'reverse' is not defined
[pid: 23394|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:50:20 2025] GET / => generated 54115 bytes in 120 msecs (HTTP/1.1 500) 7 headers in 242 bytes (1 switches on core 0)
!!! uWSGI process 23394 got Segmentation Fault !!!
*** backtrace of 23394 ***
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_backtrace+0x32) [0x565da772]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_segfault+0x35) [0x565dab55]
linux-gate.so.1(__kernel_sigreturn+0) [0xf7f8a570]
/lib/i386-linux-gnu/libc.so.6(+0x7c873) [0xf76e7873]
/lib/i386-linux-gnu/libc.so.6(+0x7d0a7) [0xf76e80a7]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xd7658) [0xf792a658]
/lib/i386-linux-gnu/libpython3.9.so.1.0(PyMem_RawFree+0x1d) [0xf792a2bd]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xd7771) [0xf792a771]
/lib/i386-linux-gnu/libpython3.9.so.1.0(PyObject_Free+0x1d) [0xf792a3dd]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0xec709) [0xf793f709]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0x1c8399) [0xf7a1b399]
/lib/i386-linux-gnu/libpython3.9.so.1.0(_PyGC_CollectNoFail+0x4f) [0xf7a1b92f]
/lib/i386-linux-gnu/libpython3.9.so.1.0(+0x1857e7) [0xf79d87e7]
/lib/i386-linux-gnu/libpython3.9.so.1.0(Py_FinalizeEx+0x22c) [0xf79f8fdc]
/lib/i386-linux-gnu/libpython3.9.so.1.0(Py_Finalize+0x14) [0xf79f9294]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_python_atexit+0xe6) [0x565e74e6]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_plugins_atexit+0x6b) [0x565d767b]
/lib/i386-linux-gnu/libc.so.6(+0x3388e) [0xf769e88e]
/lib/i386-linux-gnu/libc.so.6(+0x33a61) [0xf769ea61]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(+0x23295) [0x56588295]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(end_me+0x30) [0x565d76d0]
linux-gate.so.1(__kernel_sigreturn+0) [0xf7f8a570]
linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f8a559]
/lib/i386-linux-gnu/libc.so.6(epoll_wait+0x2c) [0xf776a83c]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(event_queue_wait+0x2f) [0x565cc95f]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(wsgi_req_accept+0x102) [0x56585532]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(simple_loop_run+0xd1) [0x565d6411]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(simple_loop+0x8a) [0x565d652a]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_ignition+0x1e2) [0x565dae12]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_worker_run+0x270) [0x565df7a0]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(uwsgi_run+0x464) [0x565dfcd4]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(+0x1f894) [0x56584894]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106) [0xf7685ed6]
/home/kolre2/Proektuvanya/Program/venv/bin/uwsgi(_start+0x31) [0x565848d1]
*** end of backtrace ***
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:52:13 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57e1c700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57e1c700 pid: 23410 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23410, cores: 1)
[pid: 23410|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:52:14 2025] GET / => generated 2348 bytes in 3245 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23410|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:52:20 2025] GET /stream/ => generated 1538 bytes in 11 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:52:40 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:52:40 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23410|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:52:20 2025] GET /video_feed/ => generated 15365253 bytes in 20401 msecs (HTTP/1.1 200) 5 headers in 203 bytes (250 switches on core 0)
corrupted double-linked list
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:53:15 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57993700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x57993700 pid: 23433 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23433, cores: 1)
[pid: 23433|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:53:17 2025] GET / => generated 2348 bytes in 1794 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23433|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:53:20 2025] GET /stream/ => generated 1538 bytes in 11 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:53:55 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:53:55 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23433|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:53:20 2025] GET /video_feed/ => generated 19626496 bytes in 35215 msecs (HTTP/1.1 200) 5 headers in 203 bytes (355 switches on core 0)
!!! uWSGI process 23433 got Segmentation Fault !!!
malloc(): unsorted double linked list corrupted
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:54:20 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x56b36700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56b36700 pid: 23458 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23458, cores: 1)
[pid: 23458|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:54:21 2025] GET / => generated 2348 bytes in 1353 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23458|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:54:24 2025] GET /stream/ => generated 1538 bytes in 8 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:54:43 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:54:43 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23458|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:54:25 2025] GET /video_feed/ => generated 11734128 bytes in 18874 msecs (HTTP/1.1 200) 5 headers in 203 bytes (204 switches on core 0)
corrupted double-linked list
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 00:54:55 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x56d95700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56d95700 pid: 23478 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23478, cores: 1)
[pid: 23478|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Mon Jun  2 23:54:56 2025] GET / => generated 2348 bytes in 2074 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23478|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Mon Jun  2 23:55:00 2025] GET /stream/ => generated 1538 bytes in 9 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Mon Jun  2 23:55:23 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Mon Jun  2 23:55:23 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23478|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Mon Jun  2 23:55:00 2025] GET /video_feed/ => generated 14604668 bytes in 22996 msecs (HTTP/1.1 200) 5 headers in 203 bytes (260 switches on core 0)
[pid: 23478|app: 0|req: 4/4] 127.0.0.1 () {44 vars in 851 bytes} [Tue Jun  3 02:00:40 2025] GET /stream/ => generated 1538 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Tue Jun  3 02:01:55 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Tue Jun  3 02:01:55 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23478|app: 0|req: 5/5] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 02:00:40 2025] GET /video_feed/ => generated 43261504 bytes in 74440 msecs (HTTP/1.1 200) 5 headers in 203 bytes (762 switches on core 0)
[pid: 23478|app: 0|req: 6/6] 127.0.0.1 () {44 vars in 832 bytes} [Tue Jun  3 02:09:23 2025] GET / => generated 2348 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 23478|app: 0|req: 7/7] 127.0.0.1 () {44 vars in 851 bytes} [Tue Jun  3 02:16:54 2025] GET /stream/ => generated 1538 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Tue Jun  3 02:17:10 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Tue Jun  3 02:17:10 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 23478|app: 0|req: 8/8] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 02:16:54 2025] GET /video_feed/ => generated 9472327 bytes in 16540 msecs (HTTP/1.1 200) 5 headers in 203 bytes (167 switches on core 0)
[pid: 23478|app: 0|req: 9/9] 127.0.0.1 () {44 vars in 851 bytes} [Tue Jun  3 02:17:52 2025] GET /stream/ => generated 1538 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Tue Jun  3 23:33:19 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x56ef5700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56ef5700 pid: 1377 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1377, cores: 1)
[ WARN:0@1.972] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.973] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
[pid: 1377|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 22:48:14 2025] GET /video_feed/ => generated 0 bytes in 2548 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
Not Found: /favicon.ico
[pid: 1377|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 22:48:16 2025] GET /favicon.ico => generated 2633 bytes in 35 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 1377|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 832 bytes} [Tue Jun  3 23:38:55 2025] GET / => generated 2348 bytes in 67 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 1377|app: 0|req: 4/4] 127.0.0.1 () {44 vars in 851 bytes} [Tue Jun  3 23:38:57 2025] GET /stream/ => generated 1538 bytes in 8 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[ WARN:0@3042.223] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@3042.223] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
[pid: 1377|app: 0|req: 5/5] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 23:38:57 2025] GET /video_feed/ => generated 0 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 203 bytes (0 switches on core 0)
[pid: 1377|app: 0|req: 6/6] 127.0.0.1 () {46 vars in 882 bytes} [Tue Jun  3 23:39:04 2025] GET /stream/ => generated 1538 bytes in 1 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Tue Jun  3 23:39:10 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Tue Jun  3 23:39:10 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 1377|app: 0|req: 7/7] 127.0.0.1 () {42 vars in 760 bytes} [Tue Jun  3 23:39:04 2025] GET /video_feed/ => generated 2779834 bytes in 5900 msecs (HTTP/1.1 200) 5 headers in 203 bytes (60 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Thu Jun  5 01:55:05 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x5768c700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5768c700 pid: 1238 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1238, cores: 1)
Not Found: /favicon.ico
[pid: 1238|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 753 bytes} [Thu Jun  5 00:57:40 2025] GET /favicon.ico => generated 2633 bytes in 5416 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Thu Jun  5 23:53:34 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57990700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57990700 pid: 1377 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 1377, cores: 1)
Not Found: /favicon.ico
[pid: 1377|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 753 bytes} [Thu Jun  5 22:56:52 2025] GET /favicon.ico => generated 2633 bytes in 6173 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
invalid request block size: 21327 (max 4096)...skip
invalid request block size: 21327 (max 4096)...skip
invalid request block size: 21327 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21327 (max 4096)...skip
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Fri Jun  6 00:41:09 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57a8c700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57a8c700 pid: 17298 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 17298, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./video_admin/urls.py", line 22, in <module>
    path('', include('cameras.urls')),
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./cameras/urls.py", line 2, in <module>
    from . import views
  File "./cameras/views.py", line 89, in <module>
    from .mongo_utils import insert_series, get_all_series, get_series_by_name
ImportError: cannot import name 'insert_series' from 'cameras.mongo_utils' (./cameras/mongo_utils.py)
[pid: 17298|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Thu Jun  5 23:41:25 2025] GET / => generated 156036 bytes in 2507 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Fri Jun  6 00:44:38 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x579fd700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x579fd700 pid: 17336 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 17336, cores: 1)
[pid: 17336|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Thu Jun  5 23:44:41 2025] GET / => generated 2348 bytes in 1905 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 17336|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 851 bytes} [Thu Jun  5 23:44:45 2025] GET /stream/ => generated 1538 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[ WARN:0@3.774] global cap_v4l.cpp:913 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@3.775] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
[pid: 17336|app: 0|req: 3/3] 127.0.0.1 () {42 vars in 760 bytes} [Thu Jun  5 23:44:45 2025] GET /video_feed/ => generated 0 bytes in 46 msecs (HTTP/1.1 200) 4 headers in 162 bytes (0 switches on core 0)
[pid: 17336|app: 0|req: 4/4] 127.0.0.1 () {46 vars in 882 bytes} [Thu Jun  5 23:44:55 2025] GET /stream/ => generated 1538 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Thu Jun  5 23:45:40 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Thu Jun  5 23:45:40 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 17336|app: 0|req: 5/5] 127.0.0.1 () {42 vars in 760 bytes} [Thu Jun  5 23:44:55 2025] GET /video_feed/ => generated 34160142 bytes in 44984 msecs (HTTP/1.1 200) 4 headers in 162 bytes (574 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
[pid: 17336|app: 0|req: 6/6] 127.0.0.1 () {42 vars in 829 bytes} [Thu Jun  5 23:47:16 2025] GET /motion_events/ => generated 17091 bytes in 14 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
[pid: 17336|app: 0|req: 7/7] 127.0.0.1 () {32 vars in 367 bytes} [Thu Jun  5 23:48:23 2025] GET /motion_events/ => generated 17091 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
corrupted double-linked list
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Fri Jun  6 01:33:35 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x57842700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x57842700 pid: 17598 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 17598, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./video_admin/urls.py", line 22, in <module>
    path('', include('cameras.urls')),
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./cameras/urls.py", line 9, in <module>
    path('series/', views.series_list_view, name='series_list'),
AttributeError: module 'cameras.views' has no attribute 'series_list_view'
[pid: 17598|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Fri Jun  6 00:33:39 2025] GET / => generated 141868 bytes in 3020 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 545, in resolve
    for pattern in self.url_patterns:
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./video_admin/urls.py", line 22, in <module>
    path('', include('cameras.urls')),
  File "/home/kolre2/Proektuvanya/Program/venv/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./cameras/urls.py", line 9, in <module>
    path('series/', views.series_list_view, name='series_list'),
AttributeError: module 'cameras.views' has no attribute 'series_list_view'
[pid: 17598|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 832 bytes} [Fri Jun  6 00:34:29 2025] GET / => generated 141868 bytes in 284 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
corrupted double-linked list
[uWSGI] getting INI configuration from /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi.ini
*** Starting uWSGI 2.0.29 (32bit) on [Fri Jun  6 01:34:45 2025] ***
compiled with version: 10.2.1 20210110 on 22 May 2025 02:56:22
os: Linux-5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
nodename: raspberry
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/kolre2/Proektuvanya/Program/video_admin
detected binary path: /home/kolre2/Proektuvanya/Program/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/kolre2/Proektuvanya/Program
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 11868
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.9.2 (default, Mar 20 2025, 02:07:39)  [GCC 10.2.1 20210110]
PEP 405 virtualenv detected: /home/kolre2/Proektuvanya/Program/venv
Set PythonHome to /home/kolre2/Proektuvanya/Program/venv
Python main interpreter initialized at 0x58145700
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 64128 bytes (62 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x58145700 pid: 17623 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 17623, cores: 1)
[pid: 17623|app: 0|req: 1/1] 127.0.0.1 () {44 vars in 832 bytes} [Fri Jun  6 00:34:47 2025] GET / => generated 2348 bytes in 2187 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 2/2] 127.0.0.1 () {44 vars in 860 bytes} [Fri Jun  6 00:34:52 2025] GET /motion_events/ => generated 17091 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 3/3] 127.0.0.1 () {44 vars in 851 bytes} [Fri Jun  6 00:34:59 2025] GET /stream/ => generated 1538 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Fri Jun  6 00:35:52 2025 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /video_feed/ (ip 127.0.0.1) !!!
Fri Jun  6 00:35:52 2025 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 429] during GET /video_feed/ (127.0.0.1)
OSError: write error
[pid: 17623|app: 0|req: 4/4] 127.0.0.1 () {42 vars in 760 bytes} [Fri Jun  6 00:34:59 2025] GET /video_feed/ => generated 50161214 bytes in 53266 msecs (HTTP/1.1 200) 4 headers in 162 bytes (788 switches on core 0)
[pid: 17623|app: 0|req: 5/5] 127.0.0.1 () {44 vars in 860 bytes} [Fri Jun  6 00:35:52 2025] GET /motion_events/ => generated 29626 bytes in 17 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 6/6] 127.0.0.1 () {44 vars in 860 bytes} [Fri Jun  6 00:35:52 2025] GET /motion_events/ => generated 29626 bytes in 16 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
[pid: 17623|app: 0|req: 7/7] 127.0.0.1 () {44 vars in 860 bytes} [Fri Jun  6 00:35:54 2025] GET /motion_events/ => generated 29626 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 160 bytes (1 switches on core 0)
